projectdir: /root/Voyage
server:
    ip_address: 0.0.0.0
    port: 80
twitter:
    initial_tweet_count: 3000
    iteration_tweet_count: 200
    from_start:  True
    min_iteration_time: 600
    wait_rate_seconds: 60
    consumer_key:
    consumer_secret:
    access_token:
    access_token_secret:
article:
    min_iteration_time: 3600
storage:
    date_format: _%Y-%m-%dT%H:%M #leave _ at the start
    # "%Y-%m-%dT%H:%M"  - Universal date format for consistency
communication:
    retry_count: 10
    retry_delta: 1
    sleep_time: 5
warc:
    max_phantoms: 5
    dir: warc
    article_subdir: article
    twitter_subdir: twitter
pdf:
    dir: pdf
    article_subdir: article
    twitter_subdir: twitter
database:
    version: 0.0.1
log:
    retention_days: 30
crawler:
    limit: 5000
